### ISSUE TITLE
Sever lag when posting to remote MySQL server

### ISSUE THREAD

**Issue by p0wd3r** [Zarius/Bukkit-OtherBlocks#295]
OtherDrops v2.8b.573
iConomy (no version listed, latest)
Vault v1.2.27-b349

When iConomy is tied to a remote MySQL server (on the same network) and OtherDrops is set up to give money for killing mobs the lag is crazy, and makes the world unplayable.  Many warnings like this...
***
[WARNING] Can't keep up! Did the system time change, or is the server overloaded?
***

Most of the rewards are configured like this one, not very complicated...

  ZOMBIE:
      - tool: ALL
        drop: MONEY
        quantity: 0.5
        chance: 100

When I change iConomy to use a local mini DB the lag goes away completely.  I'm also logging a lot of stats (stats by lolmewn v1.36-69) to the same remote server which sends a lot more data than OtherDrops does.  The CPU/RAM/Network Usage do not spike at all.

**Comment by Zarius** [comment]
OtherDrops just uses the Vault API and then Vault just uses the economy plugin's API so I presume the lag would be from the economy plugin (as OtherDrops doesn't have any DB code in it at all).  Closing this issue for the above reason and as it's quite old.
