### ISSUE TITLE
underscores not supported in player skull names

### ISSUE THREAD

**Issue by CultistO** [Zarius/Bukkit-OtherBlocks#296]
<Code YAML>
    CREATURE_SKELETON@NORMAL:
      - trigger: MOBSPAWN
        spawnedby: NATURAL
        drop: [DENY, "SKELETON@eq:head:SKULL_ITEM@Cultist_O"]
</Code>

This will produce a mob with "CultistO's Head" instead of "Cultist_O's Head" (So you cannot get certain player heads into the game. (Such as ones belonging to jeb_, and myself.))

**Comment by Zarius** [comment]
Tested in the latest version (2.8b.582) and works fine now.
