### ISSUE TITLE
Support Horse Data

### ISSUE THREAD

**Issue by CommodoreAlpha** [Zarius/Bukkit-OtherBlocks#344]
Horses have 3 types of data: skin, type, and tamed.

The skin is the horse's colour (along with patterns like spots), and is determined by data value which is an integer. The type is also determined by integer but I believe it's stored in the form of NBT; this determines whether the horse is a zombie, skeleton, donkey, etc. Tamed is a boolean value and is pretty self-explanatory (wolves already have this bit supported).

**Comment by Zarius** [comment]
Dev build now has horse data, could do with more testing.  Will post as new
beta on BukkitDev soon.

**Comment by israelcurtis** [comment]
where can I grab dev builds? the link on dev.bukkit.org seems down -- http://otherdrops.dyndns.org:8080/job/OtherDrops/

**Comment by Zarius** [comment]
Unfortunately the dev server appears to be down and I'm traveling at the
moment.  Fortunately though I uploaded the latest dev build to BukkitDev as
a beta (download version 2.8b.596).

**Comment by israelcurtis** [comment]
I saw that latest build posted, but it seems to be indicated only for 1.8? Can it still be used on 1.7.10?

**Comment by israelcurtis** [comment]
also, can you give a quick guide on syntax for using the horse data?

**Comment by Zarius** [comment]
Try horse@variant!!color!!style, e.g. horse@HORSE!!WHITE!!BLACK_SPOTS.
List of available types should be created upon the new version startup in
the OtherDrops/known_lists folder, I think only the "horse" variant uses
colors and styles (e.g. donkey, undead_horse, etc don't).

**Comment by israelcurtis** [comment]
got my skeleton horses! ^^ now will this build work with 1.7.10 too? page seemed to only indicate 1.8

**Comment by Zarius** [comment]
Sorry, was in a rush when posting :-)  Should work fine for versions from
1.6 and later.
