### ISSUE TITLE
tool: parameter not respected?

### ISSUE THREAD

**Issue by AnodyneEntity** [Zarius/Bukkit-OtherBlocks#354]
Hey there, I was just testing a few things out, and it seem as though in the following example, the tool name inside the tool parameter isn't respected and that any Arcane Door Key with the meta ID of 1 can be used to proc the following drops/commands. Or am I just doing something wrong?

    IRONCHEST_BLOCKIRONCHEST@1:
        - trigger: [LEFT_CLICK]
          permission: gtt
          tool: THAUMCRAFT_ARCANEDOORKEY@1~&bGolden Treasure Chest Key
          consumetool: 1
          message: '&3You have unlocked the &6Golden Treasure Chest&3.'
          command: ['/$ pex user %p add phatloots.loot.Golden-Treasure-Chest','/$ pex user %p remove otherdrops.custom.gtt']
        - trigger: [HIT]
          command: /$ pex user %p remove phatloots.loot.Golden-Treasure-Chest
          delay: 6000

**Comment by Zarius** [comment]
What version of OtherDrops are you running?

**Comment by AnodyneEntity** [comment]
Build 593.

**Comment by Zarius** [comment]
Did you get it working?

**Comment by AnodyneEntity** [comment]
Oh yes, I did. Sorry about not replying after so long.
