### ISSUE TITLE
Can't destroy ores.

### ISSUE THREAD

**Issue by BotQq** [Zarius/Bukkit-OtherBlocks#361]
Hello. I use Spigot 1649 and the newest build of OtherDrops. I can't destroy ores. It's my config: http://pastebin.com/6F38JKnh

**Comment by Zarius** [comment]
Hi BotQq,

I've tested your config using the latest otherdrops (2.8b.596) and can destroy ores fine (and no drops, which is the intent of your config).  Let me know if you are still having the issue and which versions of Bukkit & OtherDrops you are using.
