### ISSUE TITLE
ERROR Could not pass event LeavesDecayEvent to OtherDrops v2.8b. 582

### ISSUE THREAD

**Issue by Michus204** [Zarius/Bukkit-OtherBlocks#368]
OtherDrops version: 2.8b.582

      Description: Its spamming my console all the time, it doesnt do anything wrong, but only create lags on sever and spam console.

      Config (if applicable): otherdrops-config.yml: http://pastebin.com/kMVTDZGx
                                         otherdrops-drops.yml: http://pastebin.com/U6v7njAw

      Steps to reproduce the problem:

      1.Trying a few versions of otherdrops
      2.Configurating otherdrops.
      3.Deleting otherdrops file.
Error on pastebin: http://pastebin.com/MYn2ZbuW

**Comment by Zarius** [comment]
Duplicate issue - refer #360.
