### ISSUE TITLE
Limited permission capabilities

### ISSUE THREAD

**Issue by Rhisereld** [Zarius/Bukkit-OtherBlocks#373]
Currently the plugin allows for a permission condition, which is handy. However, the permission may only be in the format of otherdrops.custom.(something) (eg. otherdrops.custom.hunter).

This isn't very useful if I need to check for a permission used by other plugins. It makes more sense to me to allow writing the full permission string rather than forcing a prefix of "otherdrops.custom.". Is this possible to implement?

**Comment by Zarius** [comment]
This should be possible - added some code to check for a "!" at the start and treat that as a full permission, e.g.
```
permission: "!essentials.home"
```

This keeps the previous format (i.e. anything without the ! gets otherdrops.custom. pasted to the front before checking) so should not break any existing configs.

Need to test then will push to master.
