### ISSUE TITLE
BUG: Rabbit:creature vs. Rabbit meat:item

### ISSUE THREAD

**Issue by Rhisereld** [Zarius/Bukkit-OtherBlocks#374]
Currently the string for the animal rabbit and the meat item dropped by rabbits are both identified with the string "rabbit". There is no way to distinguish between the two, and setting rabbits to drop rabbit meat will also spawn a new rabbit on top of it.

**Comment by Zarius** [comment]
Will look into this - you can specify entity_<name> but no support yet for item_<name> to force a search in items, adding this could be solution - I'll look into it.

**Comment by Zarius** [comment]
Fixed in testing - added aliases raw_rabbit and rabbit_meat for the item, rabbit by itself will continue to refer to animal.   Cooked_rabbit already works as expected.

**Comment by Zarius** [comment]
Fixed in 0df580abd154178a3b0e132dd8a07b2fcfd16693
