### ISSUE TITLE
Could not pass LeavesDecayEvent to OtherDrops

### ISSUE THREAD

**Issue by Rhisereld** [Zarius/Bukkit-OtherBlocks#375]
I'm experiencing the following error upon leaves decaying. I'm using OtherDrops version 2.8b.582 and Worldguard 6.1.

16.12 20:06:54 [Server] INFO ... 13 more
16.12 20:06:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
16.12 20:06:54 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
16.12 20:06:54 [Server] INFO at sun.reflect.GeneratedMethodAccessor313.invoke(Unknown Source) ~[?:?]
16.12 20:06:54 [Server] INFO at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
16.12 20:06:54 [Server] INFO at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java:62) ~[?:?]
16.12 20:06:54 [Server] INFO Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
16.12 20:06:54 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
16.12 20:06:54 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:253) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.h(WorldServer.java:495) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at net.minecraft.server.v1_8_R3.Block.a(Block.java:299) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at net.minecraft.server.v1_8_R3.BlockLeaves.b(BlockLeaves.java:127) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at net.minecraft.server.v1_8_R3.BlockLeaves.e(BlockLeaves.java:137) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
16.12 20:06:54 [Server] INFO org.bukkit.event.EventException
16.12 20:06:54 [Server] INFO [20:06:54 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582

**Comment by Rhisereld** [comment]
And I'm using Spigot 1.8.8 if that helps.

**Comment by Zarius** [comment]
Duplicate issue - refer #360.
