### ISSUE TITLE
LAPIS_BLOCK as an alias for LAPIS_ORE overrides the actual LAPIS_BLOCK

### ISSUE THREAD

**Issue by Rhisereld** [Zarius/Bukkit-OtherBlocks#378]
Apparently "LAPIS_BLOCK" is an alias for "LAPIS_ORE". When you attempt to specify "LAPIS_BLOCK" as an object, it won't work for lapis blocks (the ones crafted from lapis lazuli). It will instead work for lapis ore.

This means the actual lapis block is unusable in OtherDrops.

**Comment by Zarius** [comment]
Fixed in testing, removed lapis_block alias.

**Comment by Zarius** [comment]
Fixed in b741d85f5998fc93c76ccb462501179b97347106
